# Dependencies
markdown:         kramdown
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data]
highlighter:      rouge

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            Nicolas Azari
tagline:          'Developement and sysadmin tutorials'
description:      'I am biodegradable'
url:              https://nicodinh.github.io/
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate

# Author Info
author:
  name:           'Nicolas Azari'
  url:            https://nicodinh.github.io/

# Social Integration
social:
  twitter:
  disqus:
  addthis_pubid:

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:
  super_proxy_url:

# Github
github:
  repo:           https://github.com/nicodinh
  feedback:

# Version Info
version:          0.0.0
